### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by Kunalgarg2100** [Felicity-buzz-2017/contest-portal-backend#5]
Allow comments for each question.
  -  Doesn't have to support replies to the comment (comment tree)
  -  Store time stamp, email of the user posting the comment
Next, modularize comments controller to another file and add a getAll comments function which takes a qno

**Comment by newbazz** [comment]
I will work on this.

**Comment by Kunalgarg2100** [comment]
Is this completed @newbazz ?

**Comment by newbazz** [comment]
Yup Yet it doesn't support replies to the comment.
